# Assignment 05 

We will use pandas to get some insights into what the Berlin Senat spends money on

In [3]:
import numpy as np
import pandas as pd

# load the data into a data frame
df = pd.read_csv("data/zuwendungen-berlin.csv.gz")
df.sample(n=10)

,Name,Geber,Art,Jahr,Anschrift,Politikbereich,Zweck,Betrag
18683,Dissens - Pädagogik und Kunst im Kontext e. V.,"Senatsverwaltung für Arbeit, Integration und F...",Projektförderung,2014,"Marzahner Promenade 33, 12679 Berlin",Arbeit,Kiezvernetzer,11654
32724,Albatros-Lebensnetz gGmbH,Bezirksamt Lichtenberg,Projektförderung,2016,"Berliner Straße 14, 13507 Berlin",Soziales,Bezirkliche Stadtteilkoordination zur Sicherun...,89123
23322,Tennis Borussia Berlin e. V.,Senatsverwaltung für Inneres und Sport,Projektförderung,2014,"Waldschulallee 34-42, 14055 Berlin",Sport,Kosten für die Beschäftigung von Übungsleitern,7915
1128,Berliner Tennis-Club 92 e. V.,Senatsverwaltung für Inneres und Sport,Projektförderung,2012,"Bruno-Bürgel-Weg 125, 12439 Berlin",Sport,Kosten für die Beschäftigung von Übungsleitern,302
1806,Club Dialog e. V.,"Senatsverwaltung für Arbeit, Integration und F...",Projektförderung,2012,"Friedrichstraße 176 - 179, 10117 Berlin",Arbeit,Kulturelle Bildung im multikulturellen Sozialr...,9005
9786,Comhard Gesellschaft für Bildung und Personale...,"Senatsverwaltung für Arbeit, Integration und F...",Projektförderung,2013,"Möllendorffstraße 52, 10367 Berlin",Arbeit,Büroassistent/-in für den europäischen Geschäf...,208260
20894,Kulturinitiative Förderband gGmbH,Senatskanzlei - Kulturelle Angelegenheiten -,Projektförderung,2014,"Wallstraße 32, Haus C, 10179 Berlin",Kultur,Kulturmanagement und Öffentlichkeitsarbeit für...,55281
3747,Infrastrukturelles Netzwerk Umweltschutz,Senatsverwaltung für Stadtentwicklung und Umwelt,Projektförderung,2012,"Dorfstraße 36, 13057 Berlin",Stadtentwicklung,Waldschularbeit (Uk 220),287100
17096,Berliner AIDS-Hilfe e. V.,Stiftung Deutsche Klassenlotterie Berlin,Projektförderung,2014,"Kurfürstenstraße 130, 10787 Berlin",Soziales,"Mitfinanzierung des Projekts ""Prävention mit j...",85000
21397,MiniKitas First gGmbH,"Senatsverwaltung für Bildung, Jugend und Wisse...",Projektförderung,2014,"Riedemannweg 6, 13627 Berlin",Jugend,Starthilfe - Schaffung von Plätzen- Kitaausbau...,25000

## Assignment 05.01

**Extract some summary statistics of the money spent by the Senat of Berlin**

Write a function ``assignment_05_01`` that takes the data frame of spendings and returns a list with

- the count
- the mean
- the standard deviation
- the minimum
- the 25% percentile
- the 50% percentile (median)
- the 75% percentile
- the maximum
 
of all spendings in a list. The data is in the subdirectory ``data`` and can be loaded by ``df = pd.read_csv("data/zuwendungen-berlin.csv.gz")``. For convenient compuation of the summary statistics check the pandas Series API for ``describe()``

```python

def assignment_05_01(df):
    spending_statistics = df. ...
    ...
    return spending_statistics

```

In [2]:
def assignment_05_01(df):
    # get values of count, mean, standard deviation, minimum, 25%,50%,75% and maximum
    
    return [
           ]

In [ ]:
def assignment_05_01_test():
    spending_statistics = np.array(
            [4.08200000e+04, 2.29215965e+05, 3.93196343e+06, 1.00000000e+02,
            4.67300000e+03, 1.64770000e+04, 6.11755000e+04, 4.87261162e+08])
    assert np.allclose(assignment_05_01(df), spending_statistics)

assignment_05_01_test()

## Assignment 05.02

**How much is each recipient of a spending receiving in total?**

Write a function ``assignment_05_02`` that takes the data frame of spendings and groups by recipient (column ``'Name'``) and then sums all money received for each recipient. Return the names of the recipients that received in total 143 Euros. 

```python

def assignment_05_02(df):
    money_received = df.groupby(['Name']). ...
    ...
    return names_of_recipients

```

In [4]:
def assignment_05_02_test():
    result = sorted(assignment_05_02(df))
    assert (result[0] == "Rock 'n' Roll Club Pinguin Berlin e. V.") & \
            (result[1] == 'Triathlongemeinschaft Sisu Berlin e. V.')

assignment_05_02_test()

## Assignment 05.03

**How much is Berlin spending on each political ressort?**

Write a function ``assignment_05_03`` that takes the data frame of spendings (spending is the column 'Betrag'), groups by political ressort (in german 'Politikbereich') and computes the 

 - minimum
 - median
 - maximum

of the spendings on each political ressort. Return the aggregates in the political ressort ('Politikbereich') 'sciences' ('Wissenschaft')

```python

def assignment_05_03(df):
    spending_per_ressort = df.groupby(['Politikbereich']). ...
    ...
    return 

```

In [6]:
def assignment_05_03_test():
    correct = np.array([500.0, 115557.5, 41852102.0])
    assert np.array_equal(assignment_05_03(df), correct)

assignment_05_03_test()

## Assignment 05.04

**How much is Berlin spending on each U-Bahn?**

Write a function ``assignment_05_04`` that takes the data frame of spendings, filters for transportation (german 'Verkehr'), groups by the specific ubahn and sums up the spendings. For the ubahn grouping you can extract the ubahn with the regular expression ``'U[1-9]'``. The function should return the ubahn names ordered from most (first element) to least expensive (last element).


```python

def assignment_05_04(df):
    df['ubahn'] = df['Zweck'].str.extract('(U[1-9])') ...
    ...
    return 

```

In [8]:
def assignment_05_04_test():
    ubahn_cost_ranking = ['U5', 'U2', 'U1', 'U6', 'U8', 'U7', 'U9', 'U3', 'U4']
    assert all([x==y for x,y in zip(assignment_05_04(df),ubahn_cost_ranking)])

assignment_05_04_test()